Repository acm-ucr/ieee-website, pull requests merged in 2023-04, with the labels that each got.

#21 title :)
  components/Title.jsx
  pages/index.js
Labels: ready to review, home page

#22 Create join Card :)
  components/JoinCard.jsx
Labels: ready to review, home page

#23 Create about page
  pages/about.js
Labels: ready to review, about page

#26 populate joincard
  components/JoinCard.jsx
  components/JoinCards.jsx
  pages/about.js
Labels: ready to review, home page

#27 create navigation bar
  components/Layout.jsx
  components/Navigation.jsx
  public/assets/ieee-only-logo-blue.svg
Labels: ready to review

#32 Add about page svg
  pages/about.js
Labels: ready to review, about page

#31 Isabel/footer
  components/Footer.jsx
Labels: home page

#33 Shing is Lazy!
  components/Title.jsx
Labels: ready to review

#38 Board card
  components/BoardCard.jsx
  pages/board.js
Labels: ready to review

#46 Menthy/cleanup
  components/Join.jsx
  pages/_document.js
  pages/about.js
  pages/index.js
Labels: ready to review

#50 added name and position props to BoardCard, implemented Bootstrap row and col in board.js
  components/BoardCard.jsx
  pages/board.js
Labels: ready to review, board page

#51 Fix Join Cards
  components/JoinCard.jsx
  components/JoinCards.jsx
  pages/index.js
Labels: ready to review

#54 updated project page
  components/Project.jsx
  pages/projects.js
  public/pictures/Micromouse1.png
  public/pictures/Micromouse2.png
Labels: ready to review, project page

#63 fix footer icon / link
  components/Footer.jsx
Labels: ready to review, clean up

#67 fix title image
  components/Title.jsx
  public/assets/TitleSVG.svg
Labels: ready to review, clean up

#71 JakeCreate/AddedAboutHomePageSVG
  components/About.jsx
Labels: home page

#68 Issy16/gears
  components/Footer.jsx
  components/Gear.jsx
  pages/about.js
Labels: ready to review, about page, framer motion

#73 Background for Landing
  components/Landing.jsx
  components/Layout.jsx
Labels: ready to review, mid, home page
